version: '3'
services:

  exchatgpt:
    build:
      context: .
      dockerfile: Dockerfile
    image: exchatgpt
    container_name: exchatgpt
    restart: unless-stopped
    working_dir: /app/
    ports:
      - "5000:5000"